name: Release ZIP
on:
  push:
    branches:
      - main
    paths:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Version from commit number
        id: version
        run: |
          VERSION=$(git rev-list --count HEAD)
          echo "Generating version $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Create ZIP
        id: zip
        run: |
          zip -r release.zip *

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: release.zip
          path: release.zip
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release.zip
          token: ${{ github.token }}
          tag: v${{ steps.version.outputs.VERSION }}
          makeLatest: true
          replacesArtifacts: true
          generateReleaseNotes: true
